### ISSUE TITLE
Ring names must be DNS safe

### ISSUE THREAD

**Issue by evanlouie** [microsoft/bedrock#1103]
**Describe the bug:**  IngressRoute names must be DNS compliant and match the regex `/[a-z-\.]+/` otherwise the manifest will fail to apply:

```
ts=2020-03-05T22:35:44.264996353Z caller=sync.go:536 component=cluster method=Sync cmd="kubectl apply -f -" took=450.661307ms err="running kubectl: The IngressRoute \"storage-service-msft_testing\" is invalid: metadata.name: Invalid value: \"storage-service-msft_testing\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')" output=
```

**To Reproduce:**

bedrock.yaml:

```yaml
rings:
  msft_testing:
    isDefault: true
services:
  ./:
    displayName: storage-service
    helm:
      chart:
        branch: master
        git: 'https://some_git_repo.com'
        path: storage-service
    k8sBackend: chart-storage-service
    k8sBackendPort: 80
    middlewares: []
    pathPrefix: ''
    pathPrefixMajorVersion: ''
variableGroups:
  - msfttestingvg
```

IngressRoutes with the name `storage-service-msft_testing` will be created. These are invalid.

**Expected behavior:** The ingress route is given a valid DNS-1123 subdomain string as a name

**Screenshots:**

**Additional context:**

**Does this require updates to documentation?:**
