### ISSUE TITLE
Documentation should accurately reflect correct definition.yaml outputs

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/bedrock#1142]
**Describe the bug:**
The instructions for [The First Workload for Bedrock](https://github.com/microsoft/bedrock/tree/docs_spk/docs/firstWorkload#a-first-workload-with-bedrock) show example outputs of `definition.yaml` with default variables, which does not accurately reflect the current functionality of `spk infra scaffold`.

**To Reproduce:**
Follow the instructions outlined in [The First Workload for Bedrock].(https://github.com/microsoft/bedrock/tree/docs_spk/docs/firstWorkload#a-first-workload-with-bedrock).

**Expected behavior:**
The `definition.yaml` example outputs should only display variables without default values. 

**Additional context:**
For example, the `definition.yaml` output for the `azure-simple` template:

```
name: cluster
source: 'https://github.com/microsoft/bedrock'
template: cluster/environments/azure-simple
version: master
variables:
  cluster_name: <insert val
  dns_prefix: <insert value>
  gitops_ssh_url: <insert value>
  gitops_ssh_key: <insert value>
  gitops_path: <insert value>
  resource_group_name: <insert value>
  ssh_public_key: <insert value>
  service_principal_id: <insert value>
  service_principal_secret: <insert value>
  vnet_name: <insert value>
```

This is related to: https://github.com/microsoft/bedrock/issues/1028

**Does this require updates to documentation?:**
Yes
