### ISSUE TITLE
SPK generated pipelines should log the version of SPK 

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1144]
**As a:**
Developer

**I want:**
`spk` generated pipelines (e.g. life-cycle, HLD to Manifest, and build) to have a YAML comment  indicating that version of SPK generated them

**So that:**
I can know what version of SPK generated the pipeline. This is will help know if I should re-generate.

**Describe the solution you'd like:**
The simplest approach would be to decorate the yaml for a pipeline like 
```
# GENERATED WITH SPK VERSION 0.5.7
trigger:
  branches:
    include:
      - master
pool:
  vmImage: ubuntu-latest
steps:
  - checkout: self
    persistCredentials: true
    clean: true
  - script: |-
      set -e
      # Download build.sh
      curl $BEDROCK_BUILD_SCRIPT > build.sh
      chmod +x ./build.sh
    displayName: Download bedrock bash scripts
    env:
      BEDROCK_BUILD_SCRIPT: $(BUILD_SCRIPT_URL)
    <...>
```

One could also use a commit hash or something.

**Does this require updates to documentation?:**
No

Related to #1082 There is a need for versioning
