### ISSUE TITLE
Issue in spk reconcile setting k8sSvcBackendAndName

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1175]
**Describe the bug:**
The `common.yaml` file produced by the `spk-reconcile` process is missing the service name. The image below shows the result of a pull request produced by the lifecycle pipeline.
<img width="684" alt="image" src="https://user-images.githubusercontent.com/3119513/76720796-0d0cf980-66fb-11ea-8392-dbefcd8361c6.png">

The code [here](https://github.com/CatalystCode/spk/blob/78ef90f4041b3692c29806102048c4223755ced3/src/commands/hld/reconcile.ts#L536) seems to be the issue. We should check for empty values before we concatenate most likely.

I suspect this might be an issue with the fact that the `bedrock.yaml` only contains a displayName and an empty k8sBackend: 
```
rings:
  master:
    isDefault: true
services:
  ./:
    displayName: quick-start-app
    helm:
      chart:
        accessTokenVariable: ACCESS_TOKEN_SECRET
        branch: master
        git: 'https://dev.azure.com/abrig/BedrockRocks/_git/quick-start-helm'
        path: quick-start-app/chart
    k8sBackend: ''
    k8sBackendPort: 0
    middlewares: []
    pathPrefix: ''
    pathPrefixMajorVersion: ''
variableGroups:
  - quick-start-vg
```

**To Reproduce:**

**Expected behavior:**
I should have a valid service name in `common.yaml`

**Screenshots:**

**Additional context:**

**Does this require updates to documentation?:**
