### ISSUE TITLE
spk init -f loaded configurations adds ">-" continuation sequence that might have issues with spk commands

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1179]
Possible issue from a customer. We should verify:

> it is suspected that if the file is provided during "spk init", the init process will form a new config.yaml file that contains ">-" continuation sequence for manifest properties.  This will cause the pipeline created by "spk hld install-manifest-pipeline" to fail. 
> 
> Removing these characters and regenerating the pipeline fixes the issue.

Moreover errors given my spk are not helpful

> In case of an error values provided in the manifest, error does not have sufficient level of detail to understand what the issue is.
> 
> info:    Attempting to authenticate with Azure DevOps organization 'Epi Change Feed Org' using PAT '************************************************qjdq'
> 
> error:   Error connecting Azure DevOps Git API
> 
> error:   Error occurred installing pipeline for HLD to Manifest pipeline
> 
> error:   Cannot read property 'value' of null

**Comment by andrebriggs** [comment]
@yradsmikham have you been able to verify this?

**Comment by yradsmikham** [comment]
@andrebriggs I am unable to reproduce the error that the user is seeing. After being able to generate a `config.yaml` with ">-", I was able to get past the authentication error shown.

Do we know where the ">-" is appearing in their `config.yaml`?

**Comment by dennisseah** [comment]
the `>-` e.g. 
```
key: >-fakeSJGTxa8Rq+0ZtAF33LAr0hh+CamlzdBFz27wRQupLde4DmwDb5hBGRd930nQYm6j0ZiEN5Myo67Y39PtA==
``` 
is generated by `yaml.safeDump` function to avoid this, we can add `lineWidth` option. 
e.g.
```
aml.safeDump(data, { lineWidth: 5000 });
```
having lineWidth as a large integer.

**Comment by yradsmikham** [comment]
@dennisseah the problem is, I was able to successfully authenticate with Azure DevOps with the ">-" appended to the beginning of the `key` parameter. I'm wondering if the ">-" was maybe part of the `access_token` variable? In which case, when the execution occurs, it was unable to parse the PAT and caused the authentication to Azure DevOps to fail.

Either way, if that's the case. We can bump the `lineWidth`. I was just unable to verify.

**Comment by yradsmikham** [comment]
I just tried appending ">-" in other areas of the `config.yaml` (i.e. before the `access_token`) and was still able to successfully authenticate with Azure DevOps.

config.yaml:

```
azure_devops:
  access_token: >-
    <access_token>
  hld_repository: 'https://dev.azure.com/yvradsmi/spk-services/_git/fabrikam-hld'
  manifest_repository: 'https://dev.azure.com/yvradsmi/spk-services/_git/fabrikam-manifests'
  infra_repository: 'https://dev.azure.com/yvradsmi/spk-services/_git/fabrikam-tf-template'
  org: yvradsmi
  project: spk-services
infra:
  terraform: v0.12.6
  helm: v2.14.3
  git: 2.17.1
  az: 2.0.71
introspection:
  dashboard:
    image: 'mcr.microsoft.com/k8s/bedrock/spektate:latest'
    name: spektate
  azure:
    account_name: ydawgie
    table_name: storage-account-table-name
    partition_key: storage-account-table-partition-key
    key: >-
      <key>
    source_repo_access_token: source_repo_access_token
    service_principal_id: <sp_id>
    service_principal_secret: <secret>
    subscription_id: <sub_id>
    tenant_id: <tenant_id>
    resource_group: yvonne
key_vault_name: null
```

output:

```
 ✘  ~/microsoft/yradsmikham/spk   master ●  spk hld install-manifest-pipeline
info:    Attempting to authenticate with Azure DevOps organization 'yvradsmi' using PAT '************************************************bcjq'
info:    Successfully connected to Azure DevOps Git API!
info:    Fetched DevOps Client
info:    Attempting to create new pipeline: fabrikam-hld-to-fabrikam-manifests defined in repository:https://dev.azure.com/yvradsmi/spk-services/_git/fabrikam-hld, branch: master, filePath: manifest-generation.yaml
info:    Creating pipeline for definition
```
