### ISSUE TITLE
error in DevOps automating the azure Voteapp

### ISSUE THREAD

**Issue by naveen10545** [microsoft/bedrock#1195]
Hi 

We are following the https://github.com/microsoft/bedrock/tree/master/docs/devops link for automating the Azure Votepp using Azure DevOps. and end up with the following error 

exit status 1: Error: unknown command \"init\" for \"helm\"\n\nDid you mean this?\n\tlint\n\nRun 'helm --help' for usage.\n"

**Comment by bnookala** [comment]
@naveen10545 it sounds like you're presently using helm3, can you you _downgrade_ helm to helm2? https://v2.helm.sh/

**Comment by naveen10545** [comment]
@bnookala  i am currently using the standard links and how can i downgrade the HELM version to 2.

**Comment by bnookala** [comment]
@naveen10545 it's unclear to us where you're seeing this error: ```exit status 1: Error: unknown command "init" for "helm"\n\nDid you mean this?\n\tlint\n\nRun 'helm --help' for usage.\n"

```

Is this in the azure devops pipelines? or locally on your computer? This is presently the latest helm2 version that you can try: https://github.com/helm/helm/releases/tag/v2.16.3

**Comment by naveen10545** [comment]
@bnookala  The error which i posted is from Azure DevOps pipeline.

**Comment by bnookala** [comment]
@naveen10545 I see - I think I've identified the problem - the pipeline yaml that's provided in the doc is a bit stale, it should be updated.

you should update your pipeline yaml to this - it installs the correct version of helm to the pipeline.

```
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- bash: |
    curl $BEDROCK_BUILD_SCRIPT > build.sh
    chmod +x ./build.sh
  displayName: Download Bedrock orchestration script
  env:
    BEDROCK_BUILD_SCRIPT: https://raw.githubusercontent.com/Microsoft/bedrock/master/gitops/azure-devops/build.sh

- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: "2.16.3"

- task: ShellScript@2
  displayName: Validate fabrikate definitions
  inputs:
    scriptPath: build.sh
  condition: eq(variables['Build.Reason'], 'PullRequest')
  env:
    VERIFY_ONLY: 1

- task: ShellScript@2
  displayName: Transform fabrikate definitions and publish to YAML manifests to repo
  inputs:
    scriptPath: build.sh
  condition: ne(variables['Build.Reason'], 'PullRequest')
  env:
    ACCESS_TOKEN_SECRET: $(ACCESS_TOKEN)
    COMMIT_MESSAGE: $(Build.SourceVersionMessage)
    REPO: $(MANIFEST_REPO)
    BRANCH_NAME: $(Build.SourceBranchName)
```
