### ISSUE TITLE
spk lifecycle pipeline should only trigger on bedrock.yaml changes

### ISSUE THREAD

**Issue by mtarng** [microsoft/bedrock#1300]
**As a:**
spk user
**I want:**
lifecycle pipelines to only run when there are changes to `bedrock.yaml`
**So that:**
I do not have unnecessary pipeline runs.
**Describe the solution you'd like:**
Add to the pipeline triggers:
```
trigger:
  branches:
    include:
      - master
  paths:
    include:
    - bedrock.yaml
```
**Acceptance Criteria:**
- [x] Above changes
- [x] Updated smoke tests with the reduced pipeline build counts.
