### ISSUE TITLE
Map different ring names to git branches 

### ISSUE THREAD

**Issue by bnookala** [microsoft/bedrock#1313]
**As a:**

SPK User

**I want:**

To map different ring names to git branches

**So that:**

My ring names don't have to be the same as the git branch names

**Describe the solution you'd like:**

Perhaps some sort of mapping in bedrock.yaml that allows a ring name to target a git branch name, allowing a user to specify a git branch to use for a ring ie

```yaml
rings:
  prod:
    targetBranch: "master"
  develop:
    targetBranch: "develop"
  qa:
    targetBranch: "test"
etc.
```

Though perhaps the ideal schema should be inverted to be branch name as the key, and the target ring name as the value ie - we should spend some time figuring out what makes sense here

```
rings:
  master:
    targetRing "prod" 
  develop:
    targetRing: "develop"
  test:
    targetRing: "qa"
```

**Acceptance Criteria:**

- [ ] SPK cli should allow me to specify which target branch i would like to use
- [ ] Bedrock yaml schema should be updated to accommodate a target branch for rings
- [ ] Lifecycle pipeline should accommodate creating ingress routes using the targetRing parameter as the header ring
- [ ] Documentation

**Describe alternatives you've considered:**

This is a preliminary investigation into how we might map different rings to branches - there may exist other methods of solving this. 

**Additional context:**

Customer request

**Does this require updates to documentation?:**

Yes
