### ISSUE TITLE
backend azurerm commented out in generated file

### ISSUE THREAD

**Issue by jsturtevant** [microsoft/bedrock#1326]
**Describe the bug:**
I was following the tutorial at https://github.com/microsoft/bedrock/blob/master/docs/multicluster.md#building-a-multi-cluster-definition.  After running `spk infra generate --project east` the generated files have the backend commented out.

`search-generated/east/main.tf`:
```
#terraform {
#  backend "azurerm" {}
#}
module "provider" {
  source = "github.com/microsoft/bedrock?ref=master//cluster/azure/provider"
}

<removed for brevity>
```

When I run `terraform init -var-file=spk.tfvars -backend-config=./backend.tfvars `

I get a warning message: "Warning: Missing backend configuration"

My folder structure is:

```
├── search
│   ├── definition.yaml
│   ├── east
│   │   └── definition.yaml
│   ├── spk.log
│   └── west
│       └── definition.yaml
├── search-generated
│   ├── east
│   │   ├── README.md
│   │   ├── acr.tf
│   │   ├── backend.tfvars
│   │   ├── main.tf
│   │   ├── spk.tfvars
│   │   └── variables.tf
│   └── west
│       ├── README.md
│       ├── acr.tf
│       ├── backend.tfvars
│       ├── main.tf
│       ├── spk.tfvars
│       └── variables.tf
```

and the `search/definition.yaml` has:

```
name: search
source: 'https://github.com/microsoft/bedrock'
template: cluster/environments/azure-single-keyvault
version: master
backend:
  storage_account_name: bedrockstorageexample
  container_name: bedrockcontainer
  access_key: 
  key: tfstate-common-infra

<removed variables for brevity>
```
**To Reproduce:**

**Expected behavior:**
Backend is wired up correctly since I specified backend configuration

**Screenshots:**

**Additional context:**

**Does this require updates to documentation?:**
maybe
