### ISSUE TITLE
Configurable Alerting based on Flux

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#311]
As an operator I want confidence that Flux is operating correctly. If Flux has any issue syncing a git repository, takes longer than usual, has issues applying git repo changes I would like a way to alerted. 

A possible solution would be to pull in the Prometheus metrics Flux emits and create a default rule in Prometheus. This should all come out the box in the Bedrock set up. There should be instructions on how to customize the rules to an operators preferences. 

Currently an operator has to manually monitor Flux logs to ensure the GitOps flows is working correctly.

Related to #262 and #351

**Comment by yradsmikham** [comment]
Flux has a configurable parameter `prometheus.enabled`. This will essentially add prometheus annotations to Flux when enabled, as shown:

```
# Source: flux/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  labels:
    app: flux
    chart: flux-0.8.0
    release: flux
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux
      release: flux
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "true"
      labels:
        app: flux
        release: flux
```

This will allow metrics like `cache_request_duration` and `client_fetch_duration` and `daemon_sync_duration` to come through to the Prometheus server, and these statistics can be visualized in Grafana. I'm not certain that these metrics can accurately capture a failing scenario for Flux. Because Prometheus is a monitoring system that only collects and process metrics, and is not an event logging system, it may not be the best option for monitoring Flux unless there is a way to retrieve more meaningful metrics. For dealing with Flux logs, we may want to use ELK or FluentD.
