### ISSUE TITLE
Backup and restore of cluster

### ISSUE THREAD

**Issue by timfpark** [Microsoft/bedrock#366]
As an operator of a cluster, I want to be able to backup and restore clusters so that, in particular for stateful cluster scenarios, I am able to quickly recover from operational failures.

For example, let's say I am an enterprise operating a large Kafka cluster in Kubernetes.  I want daily snapshot backups of this Kafka deployment, and the ability, if there is a failure, to create a new cluster and rehydrate this backup into it.

This issue covers the epic level story around operationalizing backup and restores of Kubernetes clusters:

- [ ] Installation of Velero to do this
- [ ] Establishing a scheduled backup of the cluster into Blob storage
- [ ] Establishing an operational procedure for spinning up a new cluster and restoring these backups.
- [ ] Documenting this procedure as part of the Bedrock documentation.

**Comment by timfpark** [comment]
I have this working now end to end @sarath-p - basically, I think we just need to figure out how to operationalize and document it in Bedrock the right way.   Here are the steps:

* Deploy Velero in the existing cluster with this [Fabrikate component](https://github.com/timfpark/fabrikate-velero).  Have all of your clusters share the same backup location container via a config in `common.yaml` that looks like this:

```
subcomponents:
  velero:
    config:
      azure:
        clientId: <client id>
        clientSecret: <client secret>
        storageResourceGroup: <backup storage rg>
        subscriptionId: <subscription id>
        tenantId: <tenant_id>
        storageAccount: <storage account>
        container: backups
```

Then, per cluster, have a config that points to the specific cluster RG:

eg. `green.yaml`:

```
subcomponents:
  velero:
    config:
      azure:
        clusterResourceGroup: MC_green-rg_green_eastus2
```

and `blue.yaml`:

```
subcomponents:
  velero:
    config:
      azure:
        clusterResourceGroup: MC_blue-rg_blue_eastus2
```

* Deploy a Velero periodic backup manifest ([example here](https://gist.github.com/timfpark/2bebe05b35acb8dcd0b0047c3e1827ac)) in the Fabrikate definition for your cluster.
* Let the cluster back itself up.  This will snapshot all of the attached PVC/PVs and capture the applied resource manifests.
* On operational failure of the first cluster, create the second cluster with `enable_flux` equal to `false` such that it does not provision flux initially.
* Install velero on this restore cluster (we should look at a way to do this in an automated fashion outside of flux since that is not running).
* Execute `$ velero restore create --from-backup daily-backup` and velero should restore the stateful workloads in the cluster.
* Finally, change `enable_flux` to true for the cluster, and then do a `terraform apply`.  This will provision flux in the system and flux will automatically deploy the stateless workloads as well.
