### ISSUE TITLE
As a developer, I want to initialize infrastructure for Bedrock and host the state of such environment.

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#615]
**As a:**
Developer

**I want:**
a CLI to store validation against a local environment to ensure all prerequisites are installed and authentication (to Azure) is valid.

**So that:**
The CLI is able to identify missing requirements for infrastructure deployment.

**Describe the solution you'd like:**
The CLI command should include the following functionality:
- [x] Rename `spk infra init` to `spk infra validate`
- [x] Write to `spk-config.yaml` file. For example:
```
infra:
  checks:
      terraform: true
      git: true
      az: true
      helm: true
      az_login_check: true
      env_var_check: true
  versions:
      terraform: "v0.12.6"
      helm: "v2.14.3"
      git: "2.17.1"
```
- [x] Handle "soft checks" and "hard checks". When the global `init` executes, an infra "soft check" will occur, when future `spk infra` commands execute, an infra "hard check" will occur.

Acceptance Criteria:

spk tool (CLI) will write to `spk-config.yaml`, and perform soft/hard checks.

**Does this require updates to documentation?:**
Yes
