### ISSUE TITLE
[SPK] Create IngressRoutes for new Services

### ISSUE THREAD

**Issue by evanlouie** [microsoft/bedrock#619]
**As a:**

SPK user

**I want:**

I want Ingress Routes to be automatically added to my services

**So that:**

I can have my tooling generate the necessary routing rules to accommodate rings

**Describe the solution you'd like:**

A method or a mechanism that _should_ add Ingress Routes to a service by: As
we're using Traefik ingress controller, we should create Traefik ingress routes.
This can be simply templatizing an ingress route. We want to create an Ingress
Route for the each of the rings defined in a bedrock.yaml file for my service,
and placing them in each subdirectory as a static manifest.

- [x] Produce a function/util inside spk that can output a materialized yaml
      output of a Traefik `IngressRoute` and configures it for a ring component
      in an HLD repository as a static manifest. This will be called by #717
  - `spk ingress-route create <service>  --ring <ring-name> --out /some/path/on/disk.yaml`
    - outputs the yaml file to `/some/path/on/disk.yaml`
  - `spk ingress-route create <service> --ring <ring-name>`
    - prints it out to console (useful for piping in a pipeline if needed)

**Describe alternatives you've considered:**

**Additional context:**

In order for an application to be publicly accessible, it needs a routing rule
for the ingress controller (traefik, in this case)

**Does this require updates to documentation?:**

Yes ~

**Comment by evanlouie** [comment]
Needs more flushing out

**Comment by mtarng** [comment]
@bnookala to link example routes

**Comment by bnookala** [comment]
https://docs.traefik.io/routing/providers/kubernetes-crd/#traefik-ingressroute-definition

**Comment by andrebriggs** [comment]
@bnookala @evanlouie do we know what needs to be templatized exactly given the link to the example definition above? Just trying to flushing out the unknowns.

**Comment by evanlouie** [comment]
It will be a variation of the example from the above link:

(note this is direct copy/paste from the link above)

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutefoo

spec:
  entryPoints:
    - web
  routes:
  # Match is the rule corresponding to an underlying router.
  # Later on, match could be the simple form of a path prefix, e.g. just "/bar",
  # but for now we only support a traefik style matching rule.
  - match: Host(`foo.com`) && PathPrefix(`/bar`)
    # kind could eventually be one of "Rule", "Path", "Host", "Method", "Header",
    # "Parameter", etc, to support simpler forms of rule matching, but for now we
    # only support "Rule".
    kind: Rule
    # (optional) Priority disambiguates rules of the same length, for route matching.
    priority: 12
    services:
    - name: whoami
      port: 80
      # (default 1) A weight used by the weighted round-robin strategy (WRR).  
      weight: 1
      # (default true) PassHostHeader controls whether to leave the request's Host
      # Header as it was before it reached the proxy, or whether to let the proxy set it
      # to the destination (backend) host.
      passHostHeader: true
      responseForwarding:
        # (default 100ms) Interval between flushes of the buffered response body to the client.
        flushInterval: 100ms
```

would have to be templatized to something like:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: <SERVICE>-<RING>
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`*`) && PathPrefix(`<SERIVCE-NAME>`) && Headers(`X-RING`, `<RING-NAME>`)
    kind: Rule
    services:
    - name: <SERVICE-NAME>
      port: 80
```
