### ISSUE TITLE
[Spike] Design of Infrastructure Implementation using a CLI tool

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#620]
**As a:**
Developer

**I want:**
a design doc of a CLI  implementation that deploys custom Bedrock infrastructure templates, captures cli tooling environment for infrastructure, services, and introspection while considering deployment updates and collaboration.

**So that:**
It provides a rectified approach and guideline to implementation of infra deployments in the CLI tool
 
**Describe the solution you'd like:**
Infrastructure Design documentation that can be added to - https://github.com/CatalystCode/bedrock-end-to-end-dx

**Additional context:**
https://github.com/microsoft/bedrock/issues/585

**Does this require updates to documentation?:**
Yes

**Comment by NathanielRose** [comment]
Uploaded Design to Teams-->General-->DesignReview-->BedrockCLI-spkinfra
Sample spk.config:
``` yml
---
cloud-auth:
  azure:
        az_cli:
            azure-cli: "2.0.70"
            Extensions:
                aks-preview: "0.4.14"
        # Support for Key vault / AzDO var groups / .env
        # az_auth should be moved to .env file
        az_auth:
            service_principal_id: "client-id"
            service_principal_secret: "client-secret"
            subscription_id: "subscription-id"
            tenant_id: "tenant-id"
spk:
  key-vault-name:
  infra:
    terraform_check: true
    git_check: true
    helm_check: true
    az_cli_check: true
    env_var_check: true
    terraform: "v0.12.6"
    helm: "v2.14.3"
    git: "2.17.1"
    bedrock:
        # Releases are through tags / branches
        source: "git@github.com:microsoft/bedrock.git"
        tag:
        repo_type: "Public"
        private_repo_key: # I think we need to move it to .env since it's a secret value
    az_backend:
        resource_group_name: "StorageAccount-ResourceGroup"
        storage_account_name: "abcd1234"
        container_name: "tf-state"
        key: "prod.terraform.tf-state"
  gitops:
    project-name:
    PAT:
    resource_group_name: "StorageAccount-ResourceGroup"
    storage_account_name: "abcd1234"
    storage-partition-key:
    
```
