### ISSUE TITLE
Write versions of prerequisites to `spk-config.yaml` during validation

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/bedrock#726]
**As a:**
Developer

**I want:**
to be able to find the versions of the spk prerequisites in the `spk-config.yaml` file

**So that:**
I do not run into compatibility issues when using `spk` cli.

**Describe the solution you'd like:**
In the `spk-config.yaml` file, the versions should accurately depict the version that is running:

```
infra:
  terraform: v0.12.6
  helm: v2.14.3
  git: 2.17.1
  az: 2.0.71
```

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**
Yes.
