### ISSUE TITLE
Extend bedrock.yaml services to incorporate display name

### ISSUE THREAD

**Issue by bnookala** [microsoft/bedrock#810]
**As a:**

SPK user

**I want:**

My bedrock.yaml file to track a display name for each of my services

**So that:**

I can use the display name when scaffolding pipelines, and when scaffolding my HLD

**Describe the solution you'd like:**

- [ ] `spk service create` to take a parameter for display name ie. When I invoke `spk service create fabrikam.homepage -n homepage -d packages`  the resulting bedrock.yaml should resemble: 

```
rings:
  master:
    isDefault: true
services:
  ./packages/fabrikam.homepage:
    displayName: homepage
    helm:
      chart:
        path: './components/container'
```

**Acceptance Criteria:**

Bedrock.yaml to have a field under services to track display name as a string

**Describe alternatives you've considered:**

None

**Additional context:**

It would be nice to be able to track service names as something separate than the path of the service (ie search instead of src/fabrikam.fiber.search)

**Does this require updates to documentation?:**

Yes
