### ISSUE TITLE
SPK should generate traefik strip-prefix middleware

### ISSUE THREAD

**Issue by bnookala** [microsoft/bedrock#823]
**As a:**

SPK user

**I want:**

The ingress route generated by the `spk` to strip prefixes

**So that:**

I can build my application to listen to `/` instead of `/endpoint`

**Describe the solution you'd like:**

`spk hld reconcile` should output traefik strip-prefix middlewares for services to be consumed by an ingress route:

```
--- 
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: home-release-dev
spec:
  routes:
    - kind: Rule
      match: 'PathPrefix(`/home`) && Headers(`Ring`, `release-dev`)'
      services:
        - name: home-release-dev
          port: 8000
      middlewares:
        - name: home-strip-prefix
```

and:

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: home-strip-prefix
spec:
  stripPrefix:
    prefixes:
      - /home
    forceSlash: false
```
Place this into a separate .yaml file in the same directory.

**Acceptance Criteria:**

- [ ] `spk hld reconcile` should output traefik strip-prefix middlewares for services and configure ingress routes with the middleware
see: https://blog.containo.us/traefik-2-0-6531ec5196c2

**Describe alternatives you've considered:**

Having the application listen to /endpoint is possibly an acceptable solution

**Additional context:**

Traefik passes on the entire path to the backend application, but if the backend is not listening on the path, it will not be able to handle the request, and may fail.

**Does this require updates to documentation?:**

Yes
