### ISSUE TITLE
Scaffold ingress routes with major version

### ISSUE THREAD

**Issue by bnookala** [microsoft/bedrock#832]
**As a:**

SPK user

**I want:**

bedrock.yaml to offer overrides for ingress route path prefixes and major version

**So that:**

The scaffolded ingress route resembles the routes advised by the MS Rest guidelines https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md

**Describe the solution you'd like:**

For a bedrock.yaml that resembles

```
rings:
  dev:
    isDefault: true
  prod:
services:
  homepage:
    port: 8001
    pathPrefix: homepage
    version: v1
    backend: k8s-backend-service
```

I want a scaffolded ingress route for all rings that produces a path prefix of:

/v1/homepage 

instead of using just the service name as the route 

**Acceptance Criteria:**

- A bedrock.yaml file that resembles:

```
rings:
  dev:
    isDefault: true
  prod:
services:
  homepage:
    port: 8001
    pathPrefix: homepage
    version: v1
    backend: k8s-backend-service
```

- [ ] should output a traefik ingress route that resembles:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-dev
spec:
  routes:
    - kind: Rule
      match: 'PathPrefix(`/v1/homepage`) && Headers(`Ring`, `dev`)'
      services:
        - name: k8s-backend-service-dev
          port: 8001
```

- [ ] a test to cover the correct-ness of the scenario

**Describe alternatives you've considered:**

None

**Additional context:**

We require more flexibility with the ingress routes that are being scaffolded

**Does this require updates to documentation?:**

Yes
