### ISSUE TITLE
ingress routes do not use display name

### ISSUE THREAD

**Issue by bnookala** [microsoft/bedrock#898]
**Describe the bug:**

Ingressroutes being written improperly - not using displayName attribute in service object

**To Reproduce:**

bedrock.yaml: 
```
rings:
  master:
    isDefault: true
services:
  ./:
    displayName: fabrikam-frontend-service
    helm:
      chart:
        branch: master
        git: 'https://dev.azure.com/foo/bar/baz'
        path: chart
    middlewares:
      - ''
```

will produce:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: .-master
spec:
  routes:
    - kind: Rule
      match: 'PathPrefix(`/.`) && Headers(`Ring`, `master`)'
      services:
        - name: .-master
          port: 8000
```

where the name of the ingress route, the path prefix, and the service name are all wrong (using the path to the service, instead of the display name0

**Expected behavior:**

we should be outputting the correct service name, correct ingress route name using the ingress display name, and correct path prefix

**Screenshots:**

**Additional context:**

presently we're not using `displayName` at all

**Does this require updates to documentation?:**

no

Related to #810

**Comment by andrebriggs** [comment]
Update: @bnookala says this is a 5 line fix and should have a resolution by end of day

Expected outcome from `spk service create . -n fabrikam-frontend-service`:
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fabrikam-frontend-service-master
spec:
  routes:
    - kind: Rule
      match: 'PathPrefix(`/fabrikam-frontend-service`) && Headers(`Ring`, `master`)'
      services:
        - name:fabrikam-frontend-service-master
          port: 8000
```
