### ISSUE TITLE
SPK HLD --> Manifest pipeline fails when triggered by HLD repo merge in smoke test

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#901]
**Describe the bug:**
If you run the current integration tests, the lifecycle pipeline generates a pull request for the HLD repo. Currently the integration test doesn't approve that PR. If you approve that PR manually it will add a service to the HLD component.yaml:

<img width="698" alt="image" src="https://user-images.githubusercontent.com/3119513/73035132-faadc800-3dfb-11ea-94b0-722806db08f9.png">

After that the pipeline gets triggered and will fail
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/3119513/73035173-1b761d80-3dfc-11ea-95b8-3a66b95bbbb4.png">

```

HLD path not specified, going to run fab install in current dir
time="24-01-2020 00:11:30" level=info msg="fab version 0.17.0"
time="24-01-2020 00:11:30" level=info msg="🔍  Using git: /usr/bin/git"
time="24-01-2020 00:11:30" level=info msg="🔍  Using helm: /usr/local/bin/helm"
time="24-01-2020 00:11:30" level=info msg="🔍  Using sh: /bin/sh"
time="24-01-2020 00:11:30" level=info msg="🔍  Using curl: /usr/bin/curl"
time="24-01-2020 00:11:30" level=info msg="👉  Initializing Helm"
time="24-01-2020 00:11:30" level=info msg="💾  Loading component.yaml"
time="24-01-2020 00:11:30" level=info msg="👉  Starting install for component: default-component"
time="24-01-2020 00:11:30" level=info msg="🚁  Installing component 'cloud-native' with git from 'https://github.com/microsoft/fabrikate-definitions.git'"
time="24-01-2020 00:11:30" level=info msg="🚁  Component requested latest commit: fast cloning at --depth 1"
time="24-01-2020 00:11:30" level=info msg="🚁  Cloning https://github.com/microsoft/fabrikate-definitions.git@master:head => /tmp/af005c76-7317-4279-b070-57d28e67a34c"
time="24-01-2020 00:11:31" level=info msg="🚚  Copying /tmp/af005c76-7317-4279-b070-57d28e67a34c => /home/vsts/components/cloud-native"
time="24-01-2020 00:11:31" level=info msg="🚁  Installing component 'fabrikam2019' with git from ''"
time="24-01-2020 00:11:31" level=info msg="🚁  Component requested latest commit: fast cloning at --depth 1"
time="24-01-2020 00:11:31" level=info msg="🚁  Component requested branch 'master'"
time="24-01-2020 00:11:31" level=info msg="🚁  Cloning @master:head => /tmp/c2fcdb86-7f48-41ce-a6e1-ccbfb2c1922a"
time="24-01-2020 00:11:31" level=error msg="🚫  Error occurred while cloning: '@master:head'\nexit status 128: fatal: repository '' does not exist\n"
time="24-01-2020 00:11:31" level=info msg="💾  Loading components/cloud-native/definitions/fabrikate-cloud-native/component.yaml"
time="24-01-2020 00:11:31" level=info msg="💾  Loading components/cloud-native/definitions/fabrikate-cloud-native/config/common.yaml"
Error: exit status 128
Usage:
```

Fabrikate seems to expect a git url `Installing component 'fabrikam2019' with git from ''"`

**To Reproduce:**

Could be related to a lack on necessary information in the `bedrock.yaml` similar to #900 

**Expected behavior:**
I expect the pipeline to succeed and produce yaml

**Comment by andrebriggs** [comment]
I was able to reproduce this with the existing mono-repo version of the smoke tests. Here is a look at the mono repo `bedrock.yaml`
```
rings:
  master:
    isDefault: true
services:
  ./services/fabrikam.acme.frontend:
    displayName: ''
    helm:
      chart:
        branch: master
        git: 'https://dev.azure.com/abrig/spk/_git/'
        path: services/fabrikam.acme.frontend/chart
    middlewares:
      - ''
  ./services/fabrikam.acme.backend:
    displayName: ''
    helm:
      chart:
        branch: master
        git: 'https://dev.azure.com/abrig/spk/_git/'
        path: services/fabrikam.acme.backend/chart
    middlewares:
      - ''
variableGroups:
  - fabrikam-vg
```

Here is the mono-repo structure:
```
.
├── bedrock.yaml
├── hld-lifecycle.yaml
├── maintainers.yaml
├── myNewFile.md
├── services
│   ├── fabrikam.acme.backend
│   │   ├── Dockerfile
│   │   ├── azure-pipelines.yaml
│   │   └── chart
│   │       ├── chart.yaml
│   │       └── templates
│   │           ├── deployment.yaml
│   │           └── service.yaml
│   └── fabrikam.acme.frontend
│       ├── Dockerfile
│       ├── azure-pipelines.yaml
│       └── chart
│           ├── chart.yaml
│           └── templates
│               ├── deployment.yaml
│               └── service.yaml
└── spk.log
```

Here is what the HLD repo looks like
```
.
├── component.yaml
├── fabrikam2019
│   ├── component.yaml
│   ├── config
│   │   └── common.yaml
│   ├── fabrikam.acme.backend
│   │   ├── component.yaml
│   │   ├── config
│   │   │   └── common.yaml
│   │   └── master
│   │       ├── component.yaml
│   │       ├── config
│   │       │   └── common.yaml
│   │       └── static
│   │           └── ingress-route.yaml
│   └── fabrikam.acme.frontend
│       ├── component.yaml
│       ├── config
│       │   └── common.yaml
│       └── master
│           ├── component.yaml
│           ├── config
│           │   └── common.yaml
│           └── static
│               └── ingress-route.yaml
├── manifest-generation.yaml
└── spk.log
```

Top level `component.yaml` in HLD
```
name: default-component
type: component
subcomponents:
- name: cloud-native
  source: https://github.com/microsoft/fabrikate-definitions.git
  method: git
  path: definitions/fabrikate-cloud-native
- name: fabrikam2019
  type: component
  method: git
  branch: master
```

Here is the `component.yaml` under  fabrikam2019/fabrikam.acme.frontend looks like in the HLD repo 
```
name: fabrikam.acme.frontend
subcomponents:
- name: master
  type: component
  source: ./master
  method: local
```

Here is the reconcile pipeline error:
<pre>
FAB INSTALL
HLD path not specified, going to run fab install in current dir
time="24-01-2020 07:34:56" level=info msg="fab version 0.17.0"
time="24-01-2020 07:34:56" level=info msg="🔍  Using git: /usr/bin/git"
time="24-01-2020 07:34:56" level=info msg="🔍  Using helm: /usr/local/bin/helm"
time="24-01-2020 07:34:56" level=info msg="🔍  Using sh: /bin/sh"
time="24-01-2020 07:34:56" level=info msg="🔍  Using curl: /usr/bin/curl"
time="24-01-2020 07:34:56" level=info msg="👉  Initializing Helm"
time="24-01-2020 07:34:56" level=info msg="💾  Loading component.yaml"
time="24-01-2020 07:34:56" level=info msg="👉  Starting install for component: default-component"
time="24-01-2020 07:34:56" level=info msg="🚁  Installing component 'cloud-native' with git from 'https://github.com/microsoft/fabrikate-definitions.git'"
time="24-01-2020 07:34:56" level=info msg="🚁  Component requested latest commit: fast cloning at --depth 1"
time="24-01-2020 07:34:56" level=info msg="🚁  Cloning https://github.com/microsoft/fabrikate-definitions.git@master:head => /tmp/64d5ae77-1fce-4b2e-8dc0-0ce5dd7df906"
time="24-01-2020 07:34:56" level=info msg="🚚  Copying /tmp/64d5ae77-1fce-4b2e-8dc0-0ce5dd7df906 => /home/vsts/components/cloud-native"
time="24-01-2020 07:34:56" level=info msg="🚁  Installing component 'fabrikam2019' with git from ''"
time="24-01-2020 07:34:56" level=info msg="🚁  Component requested latest commit: fast cloning at --depth 1"
time="24-01-2020 07:34:56" level=info msg="🚁  Component requested branch 'master'"
<b>time="24-01-2020 07:34:56" level=info msg="🚁  Cloning @master:head => /tmp/fbd2c993-7b95-456c-8b62-c2f78dc17255"
time="24-01-2020 07:34:56" level=error msg="🚫  Error occurred while cloning: '@master:head'\nexit status 128: fatal: repository '' does not exist\n"</b>
time="24-01-2020 07:34:56" level=info msg="💾  Loading components/cloud-native/definitions/fabrikate-cloud-native/component.yaml"
time="24-01-2020 07:34:56" level=info msg="💾  Loading components/cloud-native/definitions/fabrikate-cloud-native/config/common.yaml"
time="24-01-2020 07:34:56" level=info msg="👉  Starting install for component: cloud-native"
time="24-01-2020 07:34:56" level=info msg="👈  Finished install for component: cloud-native"
time="24-01-2020 07:34:56" level=info msg="💾  Loading components/cloud-native/definitions/fabrikate-elasticsearch-fluentd-kibana/component.json"
time="24-01-2020 07:34:56" level=info msg="💾  Loading components/cloud-native/definitions/fabrikate-elasticsearch-fluentd-kibana/config/common.yaml"
time="24-01-2020 07:34:56" level=info msg="💾  Loading components/cloud-native/definitions/fabrikate-prometheus-grafana/component.yaml"
time="24-01-2020 07:34:56" level=info msg="💾  Loading components/cloud-native/definitions/fabrikate-prometheus-grafana/config/common.yaml"
<b>Error: exit status 128</b>
Usage:
  fab install [flags]
</pre>

**Comment by andrebriggs** [comment]
@bnookala @mtarng  @evanlouie  gave you an example of what a correct top level `component.yaml` in the HLD repo should look like? Also what should the `component.yaml` for fabrikam2019/fabrikam.acme.frontend look like?

This will help in the meantime

**Comment by bnookala** [comment]
@andrebriggs here's a sample HLD that should render correctly through fabrikate: https://github.com/bnookala/rings-hld-sample

**Comment by bnookala** [comment]
@andrebriggs: after merging @edaena's fix that added `--type helm` to the chart (see https://github.com/CatalystCode/spk/pull/219), I was able to get reconcile and fab install/generate to work with the following bedrock.yaml:

```
rings:
  master:
    isDefault: true
services:
  ./services/fabrikam.acme.frontend:
    displayName: ''
    k8sServicePort: 80
    helm:
      chart:
        branch: master
        git: 'https://github.com/helm/charts'
        path: stable/wordpress
    middlewares:
      - ''
  ./services/fabrikam.acme.backend:
    displayName: ''
    k8sServicePort: 80
    helm:
      chart:
        branch: master
        git: 'https://github.com/helm/charts'
        path: stable/wordpress
    middlewares:
      - ''
variableGroups:
  - fabrikam-vg
```
