### ISSUE TITLE
spk reconcile should use `fab add --type helm`

### ISSUE THREAD

**Issue by evanlouie** [microsoft/bedrock#916]
**Describe the bug:** `spk reconcile` should specify `--type helm` when doing
`fab add` when adding the helm chart component to a ring.

See:

- https://github.com/CatalystCode/spk/blob/master/src/commands/hld/reconcile.ts#L366
- https://github.com/CatalystCode/spk/blob/master/src/commands/hld/reconcile.ts#L368

**To Reproduce:** run `spk reconcile` on a bedrock project with at least one
service with a valid IHelmConfig. Note the created component for the helm chart
is of type `component`. Causing `fab install` to fail.

- `mkdir app hld`
- `cd app`
- `spk project init`
- `spk service create my-service -n traefik -b master -p traefik -g https://github.com/containous/traefik-helm-chart.git`
- `cd ..`
- `cd hld`
- `spk hld init`
- `cd ..`
- `spk hld reconcile my-app-component hld app`
- `cat hld/my-app-component/my-service/master`
  - will yield:
    ```
    name: master
    type: component
    subcomponents:
    - name: chart
      type: component # should be of 'helm' instead of 'component'
      source: https://github.com/containous/traefik-helm-chart.git
      method: git
      path: traefik
      branch: master
    - name: static
      type: static
      method: local
      path: ./static
    ```

* subcomponent _chart_ should be of `type: helm` not `type: component`

**Expected behavior:** `spk reconcile` works properly and the underlying
`fab install` calls install the components correctly.

**Screenshots:**

**Additional context:**

**Does this require updates to documentation?:**
