### ISSUE TITLE
spk infra generate fails to generate tfvars object when boolean and numeric variables are not wrapped in quotations

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/bedrock#954]
**Describe the bug:**
`spk infra generate -p <project>` will fail when boolean and numeric values for variables in definition files are not wrapped in quotes.

**To Reproduce:**
Execute `spk infra generate` on the following:

```
name: cluster_def
source: 'https://github.com/microsoft/bedrock'
template: cluster/environments/azure-single-keyvault
version: master
backend:
  storage_account_name: "testaccount"
  access_key: "accesskey"
  container_name: "tfstate"
variables:
  acr_enabled: true
  agent_vm_count: 6
```
`spk` will create the an empty generated directory.

**Expected behavior:**
`spk.tfvars` should be generated with the appropriate terraform templates copied over to generated directory.

**Does this require updates to documentation?:**
No
