### ISSUE TITLE
HLD Reconcile: generated middleware strips the wrong path

### ISSUE THREAD

**Issue by bnookala** [microsoft/bedrock#959]
**Describe the bug:**

A generated middleware yaml from `hld reconcile` does not strip the full path that maps to the Ingress Route

**To Reproduce:**

Using this bedrock.yaml:

```
rings:
  master:
    isDefault: true
services:
  ./services/fabrikam:
    displayName: 'fabrikam'
    k8sBackendPort: 80
    k8sBackend: 'fabrikam-k8s-svc'
    pathPrefix: 'fabrikam-service'
    pathPrefixMajorVersion: 'v1'
    helm:
      chart:
        branch: master
        git: 'https://dev.azure.com/foo/bar/_git'
        path: stable/wordpress
    middlewares:
      - ''
variableGroups:
  - fabrikam-vg
```

Running `spk hld reconcile` on an application repository produces this middleware (note the prefixes):

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: fabrikam-master
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /fabrikam
```

and this ingress route (note the path path match):

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fabrikam-master
spec:
  routes:
    - kind: Rule
      match: 'PathPrefix(`/v1/fabrikam-service`) && Headers(`Ring`, `master`)'
      middlewares:
        - name: fabrikam-master
      services:
        - name: fabrikam-k8s-svc
          port: 80
```

**Expected behavior:**

The generated middleware to utilize the path prefix and the pathPrefixMajorVersion as a prefix strip ie:

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: fabrikam-master
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /v1/fabrikam-service
```

**Additional context:**

It looks like the middleware presently uses just the display name of the service

**Does this require updates to documentation?:**

No
