### ISSUE TITLE
HLD Reconcile: Use service-ring as k8s service for ingress routes and for helm configuration

### ISSUE THREAD

**Issue by bnookala** [microsoft/bedrock#960]
**As a:**

SPK User

**I want:**

My generated HLD to automatically scaffold a service name and ring name to my HLD

**So that:**

A _unique_ service name and ring configuration be consumed further downstream by helm charts that wish to expose a k8s service

**Describe the solution you'd like:**

For a bedrock.yaml with the following contents:

```
rings:
  master:
    isDefault: true
services:
  ./services/fabrikam:
    displayName: 'fabrikam'
    k8sBackendPort: 80
    k8sBackend: 'fabrikam-k8s-svc' (used for the configuration of a serviceName in config below)
    pathPrefix: 'fabrikam-service'
    pathPrefixMajorVersion: 'v1'
    helm:
      chart:
        branch: master
        git: 'https://dev.azure.com/foo/bar/_git'
        path: stable/wordpress
    middlewares:
      - ''
variableGroups:
  - fabrikam-vg
```

The following HLD is produced:
```
├── component.yaml
└── fabrikam *repository*
    ├── access.yaml
    ├── component.yaml
    ├── config
    │   └── common.yaml
    └── fabrikam *service*
        ├── component.yaml
        ├── config
        │   └── common.yaml
        └── master *ring*
            ├── component.yaml
            ├── config
            │   └── common.yaml <- ring configuration
            └── static
                ├── ingress-route.yaml <- route configuration
                └── middlewares.yaml
```

I expect the marked configuration file common.yaml available at the _ring_ level (marked above) to have the following contents:

```
subcomponents:
  chart:
    config:
      serviceName: "fabrikam-k8s-svc-master"
```

This _should_ configure a service name downstream within the helm chart to use this as a  canonical unique name for the service.

I also expect the route configuration (ingress-route.yaml, marked above) to have the following contents. Note the service name:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fabrikam-master
spec:
  routes:
    - kind: Rule
      match: 'PathPrefix(`/v1/fabrikam-service`) && Headers(`Ring`, `master`)'
      middlewares:
        - name: fabrikam-master
      services:
        - name: fabrikam-k8s-svc-master (a proper service name)
          port: 80
```

**Acceptance Criteria:**

- [x] Generated ingress route should route to a service named `$serviceName-$ring` (variables pulled from bedrock.yaml) - see sample ingress route notated above as an example ideal route
- [x] Generated config/common.yaml at the _ring_ level (see annotated tree structure above) should have `$serviceName-$ring` emitted as a configuration injected into the helm chart component. See above config/common.yaml file as a sample ideal config
- [x] Guidance on how to build a helm chart that can consume the configuration such that spk and fabrikate properly generates unique yaml for each service
- [x] A sample helm chart included within this repository that conforms to the guidance provided

**Describe alternatives you've considered:**

None - we need to be able to map a single 1 ingress route to 1 k8s service 

**Additional context:**

We presently have many ingress routes generated (1 for every ring in the service), but as we do not generate unique service names, it is very likely that many ingress routes can map to a single k8s service.

**Does this require updates to documentation?:**

Yes
